



  
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

#pragma once


#include "game_c2s_common.h"

namespace GameC2S {


	class Proxy : public ::Proud::IRmiProxy
	{
	public:
	virtual bool PlayerInput ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const nan2::PlayerInputPacket & player_input_packet) PN_SEALED; 
	virtual bool PlayerInput ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const nan2::PlayerInputPacket & player_input_packet)   PN_SEALED;  
static const PNTCHAR* RmiName_PlayerInput;
static const PNTCHAR* RmiName_First;
		Proxy()
		{
			if(m_signature != 1)
				::Proud::ShowUserMisuseError(::Proud::ProxyBadSignatureErrorText);
		}

		virtual ::Proud::RmiID* GetRmiIDList() PN_OVERRIDE { return g_RmiIDList; } 
		virtual int GetRmiIDListCount() PN_OVERRIDE { return g_RmiIDListCount; }
	};

}



