




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
using System.Net;

namespace GameC2S
{
	internal class Proxy:Nettention.Proud.RmiProxy
	{
public bool PlayerInput(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, nan2.LocalCharacterInput player_input_packet)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.PlayerInput;
		__msg.Write(__msgid);
		nan2.ProudMarshaler.Write(__msg, player_input_packet);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_PlayerInput, Common.PlayerInput);
}

public bool PlayerInput(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, nan2.LocalCharacterInput player_input_packet)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.PlayerInput;
__msg.Write(__msgid);
nan2.ProudMarshaler.Write(__msg, player_input_packet);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_PlayerInput, Common.PlayerInput);
}
#if USE_RMI_NAME_STRING
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
const string RmiName_PlayerInput="PlayerInput";
       
const string RmiName_First = RmiName_PlayerInput;
#else
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
const string RmiName_PlayerInput="";
       
const string RmiName_First = "";
#endif
		public override Nettention.Proud.RmiID[] GetRmiIDList() { return Common.RmiIDList; } 
	}
}

