




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "game_s2c_proxy.h"

namespace GameS2C {


        
	bool Proxy::PlayerSnapshot ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const nan2::LocalCharacterSnapshot & local_character_snapshot, const std::vector<nan2::RemoteCharacterSnapshot> & remote_character_snapshot)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_PlayerSnapshot;
__msg.Write(__msgid); 
	
__msg << local_character_snapshot;
__msg << remote_character_snapshot;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_PlayerSnapshot, (::Proud::RmiID)Rmi_PlayerSnapshot);
	}

	bool Proxy::PlayerSnapshot ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const nan2::LocalCharacterSnapshot & local_character_snapshot, const std::vector<nan2::RemoteCharacterSnapshot> & remote_character_snapshot)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_PlayerSnapshot;
__msg.Write(__msgid); 
	
__msg << local_character_snapshot;
__msg << remote_character_snapshot;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_PlayerSnapshot, (::Proud::RmiID)Rmi_PlayerSnapshot);
	}
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_PlayerSnapshot =_PNT("PlayerSnapshot");
#else
const PNTCHAR* Proxy::RmiName_PlayerSnapshot =_PNT("");
#endif
const PNTCHAR* Proxy::RmiName_First = RmiName_PlayerSnapshot;

}



