
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "game_s2c_common.h"
namespace GameS2C {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_PlayerSnapshot,
	};

	int g_RmiIDListCount = 1;

}


