



  
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

#pragma once


#include "game_s2c_common.h"

namespace GameS2C {


	class Proxy : public ::Proud::IRmiProxy
	{
	public:
	virtual bool PlayerSnapshots ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const nan2::LocalCharacterSnapshot & local_character_snapshot, const std::vector<nan2::RemoteCharacterSnapshot> & remote_character_snapshot) PN_SEALED; 
	virtual bool PlayerSnapshots ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const nan2::LocalCharacterSnapshot & local_character_snapshot, const std::vector<nan2::RemoteCharacterSnapshot> & remote_character_snapshot)   PN_SEALED;  
	virtual bool JoinWorld ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const std::vector<Proud::HostID> & player_ids) PN_SEALED; 
	virtual bool JoinWorld ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const std::vector<Proud::HostID> & player_ids)   PN_SEALED;  
	virtual bool PlayerJoin ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::HostID & player_id) PN_SEALED; 
	virtual bool PlayerJoin ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::HostID & player_id)   PN_SEALED;  
	virtual bool PlayerLeave ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::HostID & player_id) PN_SEALED; 
	virtual bool PlayerLeave ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::HostID & player_id)   PN_SEALED;  
static const PNTCHAR* RmiName_PlayerSnapshots;
static const PNTCHAR* RmiName_JoinWorld;
static const PNTCHAR* RmiName_PlayerJoin;
static const PNTCHAR* RmiName_PlayerLeave;
static const PNTCHAR* RmiName_First;
		Proxy()
		{
			if(m_signature != 1)
				::Proud::ShowUserMisuseError(::Proud::ProxyBadSignatureErrorText);
		}

		virtual ::Proud::RmiID* GetRmiIDList() PN_OVERRIDE { return g_RmiIDList; } 
		virtual int GetRmiIDListCount() PN_OVERRIDE { return g_RmiIDListCount; }
	};

}



