 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace GameS2C
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID PlayerSnapshots = (Nettention.Proud.RmiID)6000+1;
			public const Nettention.Proud.RmiID JoinWorld = (Nettention.Proud.RmiID)6000+2;
			public const Nettention.Proud.RmiID PlayerJoin = (Nettention.Proud.RmiID)6000+3;
			public const Nettention.Proud.RmiID PlayerLeave = (Nettention.Proud.RmiID)6000+4;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			PlayerSnapshots,
			JoinWorld,
			PlayerJoin,
			PlayerLeave,
		};
	}
}

				 
