




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "player_input_proxy.h"

namespace GameC2S {


        
	bool Proxy::PlayerInput ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const nan2::PlayerInputPacket & player_input_packet)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_PlayerInput;
__msg.Write(__msgid); 
	
__msg << player_input_packet;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_PlayerInput, (::Proud::RmiID)Rmi_PlayerInput);
	}

	bool Proxy::PlayerInput ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const nan2::PlayerInputPacket & player_input_packet)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_PlayerInput;
__msg.Write(__msgid); 
	
__msg << player_input_packet;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_PlayerInput, (::Proud::RmiID)Rmi_PlayerInput);
	}
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_PlayerInput =_PNT("PlayerInput");
#else
const PNTCHAR* Proxy::RmiName_PlayerInput =_PNT("");
#endif
const PNTCHAR* Proxy::RmiName_First = RmiName_PlayerInput;

}



