
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "player_input_common.h"
namespace GameC2S {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_PlayerInput,
	};

	int g_RmiIDListCount = 1;

}


