
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "team_mod_c2s_common.h"
namespace TeamModC2S {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_JoinTeam,
	};

	int g_RmiIDListCount = 1;

}


