




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
using System.Net;

namespace team_mod_s2c
{
	internal class Proxy:Nettention.Proud.RmiProxy
	{
public bool JoinTeam(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int team)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.JoinTeam;
		__msg.Write(__msgid);
		nan2.ProudMarshaler.Write(__msg, team);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_JoinTeam, Common.JoinTeam);
}

public bool JoinTeam(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int team)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.JoinTeam;
__msg.Write(__msgid);
nan2.ProudMarshaler.Write(__msg, team);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_JoinTeam, Common.JoinTeam);
}
#if USE_RMI_NAME_STRING
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
const string RmiName_JoinTeam="JoinTeam";
       
const string RmiName_First = RmiName_JoinTeam;
#else
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
const string RmiName_JoinTeam="";
       
const string RmiName_First = "";
#endif
		public override Nettention.Proud.RmiID[] GetRmiIDList() { return Common.RmiIDList; } 
	}
}

