
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "team_mod_s2c_common.h"
namespace team_mod_s2c {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_Snapshot,
               
		Rmi_TeamJoined,
	};

	int g_RmiIDListCount = 2;

}


