
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "team_mod_s2c_common.h"
namespace TeamModS2C {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_Snapshot,
               
		Rmi_TeamJoined,
               
		Rmi_TeamLeft,
               
		Rmi_Scored,
	};

	int g_RmiIDListCount = 4;

}


