 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace team_mod_s2c
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID Snapshot = (Nettention.Proud.RmiID)8000+1;
			public const Nettention.Proud.RmiID TeamJoined = (Nettention.Proud.RmiID)8000+2;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			Snapshot,
			TeamJoined,
		};
	}
}

				 
