



  
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

#pragma once


#include "team_mod_c2s_common.h"

namespace TeamModC2S {


	class Proxy : public ::Proud::IRmiProxy
	{
	public:
	virtual bool JoinTeam ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & team) PN_SEALED; 
	virtual bool JoinTeam ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & team)   PN_SEALED;  
static const PNTCHAR* RmiName_JoinTeam;
static const PNTCHAR* RmiName_First;
		Proxy()
		{
			if(m_signature != 1)
				::Proud::ShowUserMisuseError(::Proud::ProxyBadSignatureErrorText);
		}

		virtual ::Proud::RmiID* GetRmiIDList() PN_OVERRIDE { return g_RmiIDList; } 
		virtual int GetRmiIDListCount() PN_OVERRIDE { return g_RmiIDListCount; }
	};

}



